name: acit4610_2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - bleach=4.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - debugpy=1.8.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - ipykernel=6.29.5
  - jedi=0.19.1
  - jinja2=3.1.4
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libsodium=1.0.18
  - libstdcxx=14.1.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - mistune=2.0.4
  - nbclient=0.8.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - openssl=3.3.2
  - overrides=7.4.0
  - packaging=24.1
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.2.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.21
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=72.1.0
  - six=1.16.0
  - sniffio=1.3.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - websocket-client=1.8.0
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.1
  - zlib=1.2.13
  - pip:
      - backcall==0.2.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - docopt==0.6.2
      - fonttools==4.53.1
      - frozendict==2.4.4
      - html5lib==1.1
      - idna==3.8
      - iniconfig==2.0.0
      - ipython==8.12.3
      - kiwisolver==1.4.7
      - lxml==5.3.0
      - matplotlib==3.9.2
      - multitasking==0.0.11
      - nbconvert==7.16.4
      - numpy==2.1.1
      - pandas==2.2.2
      - peewee==3.17.6
      - pillow==10.4.0
      - pip-chill==1.0.3
      - pipreqs==0.5.0
      - pluggy==1.5.0
      - pyparsing==3.1.4
      - pytest==8.3.3
      - seaborn==0.13.2
      - soupsieve==2.6
      - tzdata==2024.1
      - webencodings==0.5.1
      - yarg==0.1.9
      - yfinance==0.2.43
      - scikit-learn==1.5.2
      - CurrencyConverter==0.17.30